import Head from 'next/head';
import { Container } from '@nextui-org/react';
import NavigationBar from '@/components/NavigationBar';

export default function Page({ children, title = 'ATP Tounaments' }: any) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationBar />
      <main>
        <Container fluid css={{ pt: 30 }}>
          {children}
        </Container>
      </main>
    </>
  );
}
